### ISSUE TITLE
Padding between popup and menu bar is too large

### ISSUE THREAD

**Issue by zvyaan** [mocki-toki/barik#71]
<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/50cfafd5-d7d1-4ba2-a684-45399fa1ef00" />

Taking a look at the image, you can see that there is too much padding between the popup and menubar. 

Running on Macbook M2 base, 13"

Here's my config:
```toml
theme = "system" # system, light, dark

[widgets]
displayed = [ # widgets on menu bar
    "default.spaces",
    "spacer",
    "default.network",
    "default.battery",
    "divider",
    # { "default.time" = { time-zone = "America/Los_Angeles", format = "E d, hh:mm" } },
    "default.time"
]

[widgets.default.spaces]
space.show-key = true        # show space number (or character, if you use AeroSpace)
window.show-title = true
window.title.max-length = 50
window.title.always-display-app-name-for = ["Mail", "Zen", "Trae"]
[widgets.default.battery]
show-percentage = true
warning-level = 30
critical-level = 10

[widgets.default.time]
format = "E d, J:mm"
calendar.format = "J:mm"

calendar.show-events = true
# calendar.allow-list = ["Home", "Personal"] # show only these calendars
# calendar.deny-list = ["Work", "Boss"] # show all calendars except these

[popup.default.time]
view-variant = "box"

[background]
enabled = true

[experimental.background] # settings for blurred background
displayed = true          # display blurred background
height = "default"        # available values: default (stretch to full screen), menu-bar (height like system menu bar), <float> (e.g., 40, 33.5)
blur = 2 
```
